packages:
  # all packages in direct subdirs of packages/
  - 'subqueries/*'
  # all packages in subdirs of components/
  - 'components/**'
  # exclude packages that are inside test directories
  - '!subqueries/common/**'
